name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ProtoBuf Compiler
        run: sudo apt-get install protobuf-compiler

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup caching
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "localcomm"

      - name: Build binaries
        run: cargo build --release --bins

      - name: Prepare binary
        run: |
          mkdir dist
          cp target/release/cli dist/localcomm-cli
          cp target/release/server dist/localcomm-server

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/localcomm-cli
            dist/localcomm-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}